[theme]
base = "light"
primaryColor = "#1D4ED8"
backgroundColor = "#D6DCE6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F172A"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[server]
headless = true
